### PR TITLE
UPDATED: Added surname of collaborator. Testing master branch protection

### PR DESCRIPTION
**Pull request by AleixMT**
This is an example of how to do a pull request in this repository. 

If you have access to the repo:
git clone it and checkout the branch. Do your changes, git add your new or removed files and git commit the changes. Finally push to a new branch. Then come to github, go to this repo, under the tab "Pull requests" create a new pull request using your newly created branch and using master as a base branch. Another collaborator has to approve the pull request. 

If you do not have access to the repo:
** fork ** this repository, git clone it and checkout the branch. Do your changes, git add your new or removed files and git commit the changes. Finally push to a new branch. Then come to github, go to this repo, under the tab "Pull requests" create a new pull request using your newly created branch and using master as a base branch. Another collaborator has to approve the pull request. 

In the message of the pull request describe the changes if necessary. In my case I just added the surname of one of the collaborators.

### CODE REVIEW

**Comment by AleixMT** [comment]
I am trying to merge it but if I ensure reviews then I cannot approve it myself.

**Comment by AleixMT** [comment]
I need approval from @AreyFerreroRamos to do this change. All changes will be reviewed by another collaborator

**Comment by AleixMT** [comment]
@AreyFerreroRamos Apruebame esta pull request si te parecen bien los cambios

**Review by AreyFerreroRamos — COMMENTED** [review]
Everything is correct

**Review by AreyFerreroRamos — CHANGES_REQUESTED** [review]
Everything is correct

**Comment by AreyFerreroRamos** [comment]
Everything is correct

**Comment by AleixMT** [comment]
No te sale una forma de aprobarla? Solamente se ha cerrado pero no se ha hecho el merge...

**Review by AreyFerreroRamos — COMMENTED** [review]
Everything is correct

**Review by AreyFerreroRamos — APPROVED** [review]
Everything is correct.

**Pull request merged**
